[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd backend && python main.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
BACKEND = "mock"
LOG_LEVEL = "info"
MAX_DRONES = "10"
SIMULATION_SPEED = "1.0"
BEARER_TOKEN = "demo-token"
API_HOST = "0.0.0.0"
